/*
-- Query: SELECT U.FIRSTNAME, U.LASTNAME, COUNT(*) AS NUMBER_OF_TASKS
FROM USERS U JOIN ISSUES I ON U.ID = I.USER_ID_ASSIGNEDTO
GROUP BY USER_ID_ASSIGNEDTO
LIMIT 0, 1000

-- Date: 2021-01-08 01:17
*/
INSERT INTO `` (`FIRSTNAME`,`LASTNAME`,`NUMBER_OF_TASKS`) VALUES ('John','Smith',8);
INSERT INTO `` (`FIRSTNAME`,`LASTNAME`,`NUMBER_OF_TASKS`) VALUES ('Zachary','Lee',7);
INSERT INTO `` (`FIRSTNAME`,`LASTNAME`,`NUMBER_OF_TASKS`) VALUES ('Stephanie','Kovalsky',6);
INSERT INTO `` (`FIRSTNAME`,`LASTNAME`,`NUMBER_OF_TASKS`) VALUES ('Thomas','Landgren',2);
