/*
-- Query: SELECT I.SUMMARY, I.DESCRIPTION, L.NAME
FROM ISSUES I
JOIN ISSUESLISTS L
LIMIT 0, 1000

-- Date: 2021-01-07 23:05
*/
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE GYM','TRAINING BY MINIMUM 1.5 H','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE GYM','TRAINING BY MINIMUM 1.5 H','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE GYM','TRAINING BY MINIMUM 1.5 H','Done');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE SHOP','BUYING POTATOES, CRANBERRIES AND COCONUT.','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE SHOP','BUYING POTATOES, CRANBERRIES AND COCONUT.','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE SHOP','BUYING POTATOES, CRANBERRIES AND COCONUT.','Done');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('STAYING AT HOME','CHECKING YOUR DUTIES LIST','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('STAYING AT HOME','CHECKING YOUR DUTIES LIST','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('STAYING AT HOME','CHECKING YOUR DUTIES LIST','Done');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('TRYING TO STAY CALM','TAKING A DEEP BREATH AND SAYING NOTHING.','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('TRYING TO STAY CALM','TAKING A DEEP BREATH AND SAYING NOTHING.','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('TRYING TO STAY CALM','TAKING A DEEP BREATH AND SAYING NOTHING.','Done');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('FINISHING THIS TASK','SAVING THIS TO THE TXT FILE.','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('FINISHING THIS TASK','SAVING THIS TO THE TXT FILE.','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('FINISHING THIS TASK','SAVING THIS TO THE TXT FILE.','Done');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE CHURCH','PRAYING FOR YOUR GRANDMATHER','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE CHURCH','PRAYING FOR YOUR GRANDMATHER','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE CHURCH','PRAYING FOR YOUR GRANDMATHER','Done');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE SKATEPARK','TRYING TO JUMP ON THE SKATEBOARD.','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE SKATEPARK','TRYING TO JUMP ON THE SKATEBOARD.','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE SKATEPARK','TRYING TO JUMP ON THE SKATEBOARD.','Done');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE FORREST','FINDING MUSHROOMS','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE FORREST','FINDING MUSHROOMS','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE FORREST','FINDING MUSHROOMS','Done');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE GYM','TRAINING BY MINIMUM 1.5 H','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE GYM','TRAINING BY MINIMUM 1.5 H','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE GYM','TRAINING BY MINIMUM 1.5 H','Done');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE SHOP','BUYING POTATOES, CRANBERRIES AND COCONUT.','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE SHOP','BUYING POTATOES, CRANBERRIES AND COCONUT.','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE SHOP','BUYING POTATOES, CRANBERRIES AND COCONUT.','Done');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('STAYING AT HOME','CHECKING YOUR DUTIES LIST','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('STAYING AT HOME','CHECKING YOUR DUTIES LIST','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('STAYING AT HOME','CHECKING YOUR DUTIES LIST','Done');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('TRYING TO STAY CALM','TAKING A DEEP BREATH AND SAYING NOTHING.','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('TRYING TO STAY CALM','TAKING A DEEP BREATH AND SAYING NOTHING.','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('TRYING TO STAY CALM','TAKING A DEEP BREATH AND SAYING NOTHING.','Done');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('FINISHING THIS TASK','SAVING THIS TO THE TXT FILE.','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('FINISHING THIS TASK','SAVING THIS TO THE TXT FILE.','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('FINISHING THIS TASK','SAVING THIS TO THE TXT FILE.','Done');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE CHURCH','PRAYING FOR YOUR GRANDMATHER','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE CHURCH','PRAYING FOR YOUR GRANDMATHER','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE CHURCH','PRAYING FOR YOUR GRANDMATHER','Done');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE SKATEPARK','TRYING TO JUMP ON THE SKATEBOARD.','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE SKATEPARK','TRYING TO JUMP ON THE SKATEBOARD.','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE SKATEPARK','TRYING TO JUMP ON THE SKATEBOARD.','Done');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE FORREST','FINDING MUSHROOMS','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE FORREST','FINDING MUSHROOMS','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE FORREST','FINDING MUSHROOMS','Done');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE GIRLFRIEND','WATCHING HORROR MOVIE ON THE NIGHT','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE GIRLFRIEND','WATCHING HORROR MOVIE ON THE NIGHT','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('GOING TO THE GIRLFRIEND','WATCHING HORROR MOVIE ON THE NIGHT','Done');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('FINDING SOME TIME FOR YOURSELF','THINKING WHAT CAN YOU DO BETTER.','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('FINDING SOME TIME FOR YOURSELF','THINKING WHAT CAN YOU DO BETTER.','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('FINDING SOME TIME FOR YOURSELF','THINKING WHAT CAN YOU DO BETTER.','Done');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('CREATING SOMETHING NEW','CREATING A POEM OR SONG','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('CREATING SOMETHING NEW','CREATING A POEM OR SONG','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('CREATING SOMETHING NEW','CREATING A POEM OR SONG','Done');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('BUYING 1 KG NUTELLA','EATING IT IN 15 MINUTES.','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('BUYING 1 KG NUTELLA','EATING IT IN 15 MINUTES.','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('BUYING 1 KG NUTELLA','EATING IT IN 15 MINUTES.','Done');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('PLAYING FIFA 21','TRYING TO WIN THE CUP.','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('PLAYING FIFA 21','TRYING TO WIN THE CUP.','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('PLAYING FIFA 21','TRYING TO WIN THE CUP.','Done');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('CALLING TO THE FAMILY','TELLING THEM HOW IMPORTANT THEY ARE','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('CALLING TO THE FAMILY','TELLING THEM HOW IMPORTANT THEY ARE','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('CALLING TO THE FAMILY','TELLING THEM HOW IMPORTANT THEY ARE','Done');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('CHECK IF THERE IS EVERYTHING DONE','WASHING THE DISHES, CLEANING THE HOUSE.','ToDo');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('CHECK IF THERE IS EVERYTHING DONE','WASHING THE DISHES, CLEANING THE HOUSE.','In progress');
INSERT INTO `` (`SUMMARY`,`DESCRIPTION`,`NAME`) VALUES ('CHECK IF THERE IS EVERYTHING DONE','WASHING THE DISHES, CLEANING THE HOUSE.','Done');
